---
sudo: required

    

services:
  - docker
before_install:
  - gem install travis --no-document
  - IMG_VERSION=`grep int version.yml | cut -d ":" -f 2`
  - KUBE_VERSION=`grep kube version.yml | cut -d ":" -f 2`

  - echo "${IMG_VERSION}"
  - echo "${KUBE_VERSION}"

script:
  - echo "${IMG_VERSION}"
  - docker login --username "davincizhao" --password-stdin <<< "${Docker_hub_pass}"
  - docker pull davincizhao/busybox:"${IMG_VERSION}"
  - sudo pip --quiet install yamllint
  - make version
