---
sudo: required

    

services:
  - docker
before_install:
  - gem install travis --no-document
  - travis version
  - travis login --pro --github-token "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"
  - IMG_VER=`cat version.yml`
  - echo "${IMG_VER}"
  - travis env set IMAGE_VERSION "${IMG_VER}" 


script:
  - docker login --username "davincizhao" --password-stdin <<< "${Docker_hub_pass}"
  - docker pull davincizhao/busybox:"${IMAGE_VERSION}"
  - docker run davincizhao/busybox:"${IMAGE_VERSION}"
  - docker ps -a
  - sudo pip --quiet install yamllint
  - echo "${IMAGE_VERSION}"
