---
sudo: required

services:
  - docker
before_install:
  - ruby -v
  - gem install travis --no-document
  - gem version
  - travis version

before_script: ./get_version.sh


script:
  - docker login --username "davincizhao" --password-stdin <<< "${Docker_hub_pass}"
  - docker pull davincizhao/busybox:"${IMAGE_VERSION}"
  - docker run davincizhao/busybox:"${IMAGE_VERSION}"
  - docker ps -a
  - sudo pip --quiet install yamllint
  - echo "${IMAGE_VERSION}"
