sudo: required

services:
  - docker

before_install:
- docker login --username davincizhao --password-stdin <<<  "${Docker_hub_pass}"
- docker pull davincizhao/busybox:v1.0.0
- docker run davincizhao/busybox
- docker ps -a


